# Generated by Django 4.2.11 on 2025-11-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_secretaria_classrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_type',
            field=models.CharField(choices=[('AULA', 'Aula'), ('LABORATORIO', 'Laboratorio')], max_length=20),
        ),
    ]
