# Generated by Django 4.2.11 on 2025-11-15 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_secretaria_classrooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'ordering': ['course__course_code', 'group_code'], 'verbose_name': 'Grupo de Curso', 'verbose_name_plural': 'Grupos de Curso'},
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='room',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='start_time',
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_role': 'PROFESOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='persistence.coursegroup')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='persistence.classroom')),
            ],
            options={
                'verbose_name': 'Bloque de Horario',
                'verbose_name_plural': 'Bloques de Horario',
                'db_table': 'schedules',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('course_group', 'day_of_week', 'start_time')},
            },
        ),
    ]
