# Generated by Django 4.2.11 on 2025-11-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_alter_coursegroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='last_student_upload_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última carga de alumnos.', null=True),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='students_loaded',
            field=models.BooleanField(default=False, help_text='Indica si ya se ha realizado una carga de alumnos para este grupo.'),
        ),
    ]
