# Generated by Django 4.2.11 on 2025-11-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0005_coursegroup_last_student_upload_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='Código'),
        ),
    ]
