# Generated by Django 4.2.11 on 2025-11-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0006_alter_classroom_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitutorygraderecord',
            name='exam_enrollment',
        ),
        migrations.RemoveField(
            model_name='substitutorygraderecord',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='SubstitutoryExamEnrollment',
        ),
        migrations.DeleteModel(
            name='SubstitutoryGradeRecord',
        ),
    ]
