# Generated by Django 4.2.11 on 2025-11-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0007_remove_substitutorygraderecord_exam_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabi/%Y/%m/', verbose_name='Archivo PDF del Sílabo'),
        ),
    ]
